// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Invoke(arg1, arg2) {
  return window['go']['controller']['App']['Invoke'](arg1, arg2);
}
