// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';
import {controller} from '../models';

export function Emit(arg1:model.EmitEvent,arg2:any):Promise<void>;

export function Invoke(arg1:string,arg2:string,arg3:controller.InvokeOption):Promise<string>;
